### ISSUE TITLE
[Feature Request] Template Scaling

### ISSUE THREAD

**Issue by AzureCamel** [vtt-lair/simbuls-creature-aide#1]
5e helpers has an option to scale and convert templates. The exact feature is called Diagonal Template Scaling. It would be amazing if that could be added in this module, or maybe a completely different one. Thank you for converting the other aspects of 5e helpers so far!

**Comment by KenGitsIt** [comment]
I never used Diagonal Template Scaling, and so if it is done, I would vote for it to be in a separate module.  I am very happy about the decision already to divide the functionality of this module from the Wild Magic Surge one.  One of the problems with the old 5e Helpers module was that it combined too much unrelated stuff into one module, making it somewhat bloated.  I strongly suspect that this is a major reason why the developers of it felt too overwhelmed to upgrade the whole thing to v10.

**Comment by vtt-lair** [comment]
Yeah, I plan to split most everything into their own modules. So Template Scaling will be it's own, and Cover as well.
Those are the next two I will do... and if there is enough requests for the others, in time I'll do them.

**Comment by KenGitsIt** [comment]
Thank you so much for doing this!

**Comment by vtt-lair** [comment]
@AzureCamel and @KenGitsIt, just release Simbul's Template Scaling. This has the 5/5/5 diagonal template scaling functionality from DnD 5e Helpers:

https://foundryvtt.com/packages/simbuls-template-scaling
