### ISSUE TITLE
Unded Fortitude Calculation is wrong

### ISSUE THREAD

**Issue by Zavian** [vtt-lair/simbuls-creature-aide#13]
As to the latest version available (1.1.4) the calculation for Undead Fortitude, as per the rules, seems to be wrong. Currently, it looks like the calculation is based on the **damage taken** rather than the **damage rolled**. In this case, Undead Fortitude, in practice, when a monster is at 1 HP the DC will always be 6 (damage taken = 1 because it can only take 1 damage to drop to 0 hp), however the rules state that the calculation is done with damage roll.

For example, if a damage roll is 15 the DC of Undead Fortitude is 20 (5 + Damage Rolled), regardless of how much thee monster started its HP as.

Image as an example https://i.imgur.com/Hd3QcuP.png
The damage roll is 10, however the DC is 6 because the zombie had 1 HP when the damage was rolled, clearly demonstrating that the calculation is based on damage taken and not the damage rolled.

Further reading and source: https://rpg.stackexchange.com/questions/164151/is-the-undead-fortitude-traits-dc-based-on-damage-dealt-or-damage-taken

**Comment by Zavian** [comment]
As a quick fix for anyone that is also sturggling with this issue (I don't really know exactly if its the proper way of doing it but it works with my limited testing)
at line 79 of ``Undead Fortitude.js`` you can edit this:
```js
const originalHp = actor.system.attributes.hp.value;
const finalHp = getProperty(update, "system.attributes.hp.value") ?? originalHp;
const hpDelta = originalHp - finalHp;
```

to this:
```js
const originalHp = actor.system.attributes.hp.value;
const damageDone = options.damageItem.appliedDamage;
const finalHp = getProperty(update, "system.attributes.hp.value") ?? originalHp;
// const hpDelta = originalHp - finalHp;
const hpDelta = damageDone
```

**Comment by vtt-lair** [comment]
Just note the above solution supplied by @Zavian will only work if you have mid-QOL also running as the options.damageItem comes from that module. If you don't run it, that won't work.

I'll make the change dependent on whether you have midi or not. The original code as DnD 5e Helpers made the assumption that you don't have midi and also at the time midi didn't have that value.

**Comment by vtt-lair** [comment]
Release 1.1.5 has this fix in, thanks @Zavian
