### ISSUE TITLE
Regeneration does not seem to be working

### ISSUE THREAD

**Issue by GambetTV** [vtt-lair/simbuls-creature-aide#19]
This is for v12 of Foundry, v3.3.1 of DnD5e, and v1.2.0 of Creature Aide (1.1.0 of Athenaeum).

Regeneration does not seem to be working. This is with no other modules active. When their turn comes around, nothing happens.

EDIT: Okay, I take that back, it is working for some NPCs, but not others. I consistently cannot get it to work for a specific NPC, even when I drag over a Regeneration item from another creature that it is working on.

2nd EDIT: Okay I think I've figured it out. It has something to do with the Effects on them. It's not working correctly. I know if they have an effect called "No Regeneration" then it's not supposed to work, but if I put a single Passive or Temporary Effect on them, simply called "New effect" and nothing else filled out in it, it'll block it.

**Comment by vtt-lair** [comment]
Thanks for the debugging, I'll have a look to see why this is happening

**Comment by vtt-lair** [comment]
Fix with release 1.2.1 @GambetTV
