### ISSUE TITLE
[Bug] Undead Fortitude Damage Clamping

### ISSUE THREAD

**Issue by harrisog** [vtt-lair/simbuls-creature-aide#4]
Undead Fortitude save DCs are currently being calculated using only the damage done to reduce the target to 0 hp, i.e. a zombie with 1 hp is always rolling a DC 6 save (with a +3 bonus lol)

**Comment by vtt-lair** [comment]
@harrisog is this for the Advanced calulcation? The one that prompts you for the damage and auto fills it?

If so, I'll have a look. I know the original didn't have the auto-fill and this could be why. Will have a look tonight.

**Comment by harrisog** [comment]
Both "quick" and "advanced" methods as far as I can tell. Tested this with minimal mods loaded in before reporting, although one of them was midi-qol

**Comment by vtt-lair** [comment]
**Without midi:**

_Quick Saves_
Zombie has 12 health, takes 13 damage
![image](https://user-images.githubusercontent.com/33215552/198061324-50f2290f-6356-4ecf-835a-c9bd324e4ea5.png)

DC is 5 + 13
![image](https://user-images.githubusercontent.com/33215552/198061393-977fb67f-587e-47ff-93b6-efd637d4b660.png)
---
Zombie has 12 health, takes 25 damage
![image](https://user-images.githubusercontent.com/33215552/198061324-50f2290f-6356-4ecf-835a-c9bd324e4ea5.png)

DC is 5 + 25:
![image](https://user-images.githubusercontent.com/33215552/198061580-ff69bbfd-8972-40ce-8975-3b57ea164588.png)

----
_Advanced Saves_
Zombie has 12 health, takes 13 damage
Damage to target is auto populated with 13, but you can put anything there:
![image](https://user-images.githubusercontent.com/33215552/198059998-1daac4cd-90cf-4ca9-874d-5d158d467aad.png)

DC is thus 5 + 13
![image](https://user-images.githubusercontent.com/33215552/198060223-68be173a-7b3d-4c21-8e43-54559494c6c6.png)
---
Zombie has 12 health, takes 13 damage, damage is autopopulated:
![image](https://user-images.githubusercontent.com/33215552/198062019-3b2ecc31-935f-4ed6-a3ce-7483fd2208f9.png)

But it's overwritten to 27:
![image](https://user-images.githubusercontent.com/33215552/198062103-e000b6d4-6fbe-4b90-a770-6c409f867628.png)

DC is thus 5 + 27
![image](https://user-images.githubusercontent.com/33215552/198062202-fa33f5ff-b8f2-4a31-8ca3-8df523892b16.png)


Will make a separate post for with midi, to see what happens (don't have midi installed on my development version, so give me a few minutes to set everything up)

**Comment by vtt-lair** [comment]
Seems like it's related to midi. As midi only does enough damage to take it to 0 and not overkill. Looking at the original design of the Undead Fortitude feature in DnD5e Helpers, this is exactly what the "Advanced" options was created for.

The "Quick" one doesn't take overkill into account when using midi.
The "Advanced" is there so that you can override midi who doesn't add overkilling damage and enter the value of the actual damage. I just populate it with the damage received from midi, but you can override it.

As such, I'm flagging this as closed as it's acting in the expected way.
