### ISSUE TITLE
SUGGESTION: Ability to create more than one name for Undead Fortitude

### ISSUE THREAD

**Issue by turboraton** [vtt-lair/simbuls-creature-aide#5]
Hello there Simbul, MANY thanks for updating this amazing module. I had this little suggestion, how about if we could create more than one name for Undead Fortitude. In my campaigns I have custom names for abilities similar to Undead Fortitude (like the Orc one or some cultist zeal). It would be amazing if you could add more names, I'll provide a picture for better explanation 
![image](https://user-images.githubusercontent.com/70917100/200651658-9c8c27dc-2e78-4a2b-92d5-ea68df6023f6.png)

**Comment by vtt-lair** [comment]
Sorry for taking so long to get back to you. Life and all that.

There currently is an ability to flag that the actor has an "Undead Fortitude like" ability:
![image](https://user-images.githubusercontent.com/33215552/206851490-eb34bdbf-a52d-4b54-9ae9-16a8d83e5a8a.png)

If you go to the Special Traits on the actor and set that flag, then it will act as if it has the ability without checking the name.
