### ISSUE TITLE
Auto-Healing the token for Undead Fortitude does not seem to work

### ISSUE THREAD

**Issue by nschoenwald** [vtt-lair/simbuls-creature-aide#8]
Using current foundry and dnd5e system version; when rolling a save that passes the DC for Undead Fortitude, the token is not healed for 1 hp.

**Comment by vtt-lair** [comment]
I just ran a test manually changing the health and rolling a sucess as well as using midi-qol. In both cases the token was healed to 1 HP.

I tested this with the both the Quick Save and the Advanced save. 

Which version of Foundry and D&D are you on?

**Comment by nschoenwald** [comment]
I think this might be an incompatibility with Ready Set Roll? In console it says that the result could not be parsed.

<img width="653" alt="image" src="https://user-images.githubusercontent.com/72390280/217857869-d20f5851-0d0c-4f15-b115-ba3f0799578c.png">

**Comment by vtt-lair** [comment]
Yes, that seems to be the culprit. Looking at the comments in the code (DnD5e Helpers - where this module was split from) didn't support Better Rolls, which is the previous module that Ready Set Roll is based on.

![image](https://user-images.githubusercontent.com/33215552/217884653-b00cd649-b9ed-4754-8a6a-002397f9539d.png)

Doesn't look like there would be a way to handle this unfortuantely.
